/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_priva_tango_clang_ClangFormat */

#ifndef _Included_com_priva_tango_clang_ClangFormat
#define _Included_com_priva_tango_clang_ClangFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_priva_tango_clang_ClangFormat
 * Method:    clang_format
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_priva_tango_clang_ClangFormat_clang_1format
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
